export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";
export const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";
export const UPDATE_AMOUNT = "UPDATE_AMOUNT";
export const UPDATE_SIZE = "UPDATE_SIZE";
